package com.example.codeclan.news.components;

import com.example.codeclan.news.models.Article;
import com.example.codeclan.news.models.Category;
import com.example.codeclan.news.models.Journalist;
import com.example.codeclan.news.repositories.articles.ArticleRepository;
import com.example.codeclan.news.repositories.categories.CategoryRepository;
import com.example.codeclan.news.repositories.journalists.JournalistRepository;
import javafx.beans.binding.When;
import org.aspectj.lang.annotation.After;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import javax.persistence.criteria.From;
import java.awt.print.Book;
import java.time.LocalDateTime;
import java.util.*;

@Component
public class DataLoader implements ApplicationRunner {

    @Autowired
    ArticleRepository articleRepository;

    @Autowired
    CategoryRepository categoryRepository;

    @Autowired
    JournalistRepository journalistRepository;

    public DataLoader() {

    }

    public void run(ApplicationArguments args) {

        Journalist johnSmith = new Journalist("John", "Smith", "Journalist", "blank.jpg", "Several years' experience, specialises in Technology.", "@johnsmith2018");
        journalistRepository.save(johnSmith);

        Journalist petraCook = new Journalist("Petra", "Cook", "Senior Journalist", "blank.jpg", "Lead editor in Sport.", "@petracook");
        journalistRepository.save(petraCook);

        Journalist maryPeterson = new Journalist("Mary", "Peterson", "Journalist", "blank.jpg", "Travel Blog lead since 2014", "@marypeterson");
        journalistRepository.save(maryPeterson);

        Journalist samLloyd = new Journalist("Sam", "Lloyd", "Senior Journalist", "blank.jpg", "Chief Politics correspondent", "@samlloyd");
        journalistRepository.save(samLloyd);

        Journalist keithGreen = new Journalist("Keith", "Green", "Journalist", "blank.jpg", "Trainee, specialising in Health topics.", "@keithgreen");
        journalistRepository.save(keithGreen);

        Category technology = new Category("Technology");
        categoryRepository.save(technology);

        Category health = new Category("Health");
        categoryRepository.save(health);

        Category travel = new Category("Travel");
        categoryRepository.save(travel);

        Category politics = new Category("Politics");
        categoryRepository.save(politics);

        Category sport = new Category("Sport");
        categoryRepository.save(sport);

        LocalDateTime date1 = LocalDateTime.of(2018, Calendar.OCTOBER, 19, 14, 15, 30);
        LocalDateTime date2 = LocalDateTime.of(2018, Calendar.OCTOBER, 19, 14, 20, 30);
        LocalDateTime date3 = LocalDateTime.of(2018, Calendar.JUNE, 22, 17, 1, 34);
        LocalDateTime date4 = LocalDateTime.of(2017, Calendar.NOVEMBER, 15, 17, 5, 45);
        LocalDateTime date5 = LocalDateTime.of(2017, Calendar.SEPTEMBER, 8, 07, 10, 40);
        LocalDateTime date6 = LocalDateTime.of(2018, Calendar.AUGUST, 10, 14, 15, 20);
        LocalDateTime date7 = LocalDateTime.of(2018, Calendar.OCTOBER, 16, 20, 20, 40);
        LocalDateTime date8 = LocalDateTime.of(2017, Calendar.FEBRUARY, 15, 16, 30, 23);
        LocalDateTime date9 = LocalDateTime.of(2018, Calendar.FEBRUARY, 23, 20, 40, 56);
        LocalDateTime date10 = LocalDateTime.of(2016, Calendar.DECEMBER, 29, 17, 50, 35);
        LocalDateTime date11 = LocalDateTime.of(2016, Calendar.NOVEMBER, 30, 18, 10, 21);
        LocalDateTime date12 = LocalDateTime.of(2017, Calendar.SEPTEMBER, 1, 10, 20, 50);
        LocalDateTime date13 = LocalDateTime.of(2018, Calendar.JUNE, 4, 12, 20, 45);
        LocalDateTime date14 = LocalDateTime.of(2017, Calendar.AUGUST, 15, 13, 30, 23);
        LocalDateTime date15 = LocalDateTime.of(2017, Calendar.OCTOBER, 18, 15, 50, 30);
        LocalDateTime date16 = LocalDateTime.of(2018, Calendar.SEPTEMBER, 23, 17, 34, 35);
        LocalDateTime date17 = LocalDateTime.of(2018, Calendar.OCTOBER, 20, 16, 36, 34);
        LocalDateTime date18 = LocalDateTime.of(2018, Calendar.MAY, 28, 20, 28, 56);
        LocalDateTime date19 = LocalDateTime.of(2017, Calendar.JUNE, 1, 21, 59, 46);
        LocalDateTime date20 = LocalDateTime.of(2018, Calendar.APRIL, 8, 22, 38, 30);
        LocalDateTime date21 = LocalDateTime.of(2016, Calendar.DECEMBER, 9, 23, 18, 31);
        LocalDateTime date22 = LocalDateTime.of(2017, Calendar.JUNE, 18, 07, 29, 25);
        LocalDateTime date23 = LocalDateTime.of(2018, Calendar.AUGUST, 26, 06, 9, 45);
        LocalDateTime date24 = LocalDateTime.of(2018, Calendar.OCTOBER, 9, 03, 10, 35);

        String copy1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non sodales tortor, et interdum ante. Suspendisse sit amet scelerisque ante. Nulla sollicitudin, lorem id ullamcorper pharetra, mi ipsum mollis lectus, et euismod nibh nisi non neque. Pellentesque non maximus est. Ut aliquam leo ut justo convallis, id tristique nunc vestibulum. Nulla a lacus urna. Aliquam pulvinar commodo enim. Sed et mauris auctor elit posuere luctus a vitae augue. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti. In hac habitasse platea dictumst. Quisque non odio et nisl bibendum lobortis sed eget augue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam elit dolor, vulputate a lobortis quis, sollicitudin quis mauris. Mauris varius magna vel tellus gravida, ac molestie turpis rhoncus. In dapibus id sem vulputate dictum. Duis vel felis sit amet eros sodales tristique. Morbi nisi diam, tincidunt bibendum nisi ac, gravida vestibulum massa. Proin tempor nisl iaculis elit accumsan consequat eget laoreet odio. In egestas dui vitae imperdiet consectetur. Maecenas molestie tellus ligula, at vestibulum purus varius a. Nunc a ultricies tellus, vitae laoreet ipsum. Mauris eget euismod elit. Quisque consectetur mi turpis, a mollis purus consequat eget.";
        String copy2 = "We arrived to Hoi An fairly late at night, however when we did arrive we were pleasantly surprised at the hotel. The hotel itself was a rather lovely building but when we got to our room we found it had been prepared in such a way to make it feel special. There were flowers on the bed, a little message and even a little story waiting for us. It just felt very considered and gave a nice touch to the beginning of our stay. \n The next morning we were up and off fairly early for a walk with our guide to show us around the city. We made our way towards the old town but even on the way there was some rather nice architecture. It felt very different from the modern cities we had been spending time in basically since Malaysia.\n A ticket was required to be in the old town. They didn't check it on entry or exit, however I believe if you were caught without it you could be fined. The ticket included entry to some historical buildings as well as some shows, however unfortunately we didn't really have enough time in Hoi An to take full advantage of all the ticket had to offer.\n We were walked around the old town, and I was in awe. It was just so beautiful and it looked like it had come straight off a postcard. I am pretty sure it was a total tourist trap, and not \"authentic\" but to be honest that didn't bother me it was beautiful and clearly was daily life for those who lived in the area.";
        String copy3 = "The most touristy activity possible in Cambodia is going to watch the sun rise behind Angkor Wat. So after a few days in Siem Reap we gave in and booked a tuk tuk to take us there, leaving our hotel at 4:30am.\nAs we arrived it was still pitch dark and we both instantly regretted not thinking to bring our head torches, but we had our phones so that was good enough. We debated a bit where to stand, I had seen plenty of photos of Angkor Wat at sunrise on the internet and I knew most of them had water in front of it so I wasn't sure if they were taken from the other side of the moat or if there was more water closer to the Wat.\n From the vague outline I could see in the sky that was beginning to lighten ever so slightly I decided we weren't close enough, after looking on google maps we saw that there were in fact two smaller bodies of water within the outer walls, so we went in search of them.\n As we approached we saw that the bodies of water were on either side of the main walkway and judging by the number of lights there, the one on the left hand side looked like it was already pretty crowded (we found out later that is because it is the \"northern reflecting pool\" while the southern one doesn't have a name so is probably less popular). So we headed to the other pool, which it turned out only had two people there when we turned up.\n We chose some spots to stand, or at least I stood and my husband sat down and tried to set up a time lapse on his phone. We soon found out we weren't standing close enough to the water for people not to come and stand directly in front of us. I am afraid I was a bit rude to one lady who did just that, but she hadn't realised, and I did apologise to her later, it was just so early in the morning. Because this incident happened fairly early on, I ended up right on the water's edge and my husband gave up on sitting and set his phone up right at my feet and then stood back a bit. He took photos of the crowd later on in the morning.";
        String copy4 = "While in Tokyo we had a few experiences with robots that I would like to share with you, most of these are not necessarily robots in the traditional sense, but more for entertainment. We have been to Tokyo before and at that point we did most of the touristy things, including seeing Asimo, so this time we just decided to have some fun.\nThe first robot we saw was also the first thing we did in Tokyo thanks to my husband, as he was obsessed with going to see this Robot for months before we even got here. I am talking about Unicorn Gundam. The first time we were in Tokyo we saw the original Gundam, but it has since been replaced by Unicorn Gundam.\nUnless you are very into Japanese culture, you are probably fairly lost right now. Mobile Suit Gundam is an anime series that started in the eighties. It is basically the story of a boy genius who uses the giant robot suit, designed by his father, to fight in and end the war raging in the galaxy. You may be more familiar with Power Rangers, which was the live action show inspired by Gundam but was more focused on selling toys. As with a lot of these types of series, it went through a series of generations of bigger, more powerful robots, including Unicorn Gundam.\nSo at Gundam Front there is a life-sized replica, previously of the original RX-78-2 Gundam and now Unicorn Gundam. It is quite impressive to see a giant robot in front of a shopping mall.\nWe did a lot of wandering around Tokyo and while I intend to dedicate a post to just that later on, one thing we came across during our wanderings was relevent to this post. We were just wandering through a mall relatively close to Gundam front where we saw a lady behind an information desk, except it wasn't a lady it was actually a robot!";
        String copy5 = "When Amirah Cook and her husband Jarrell set off on their honeymoon they had one goal: see the world. \n Want to travel the world? Here's how to budget and plan so that you can achieve your backpacker, or luxury lifestyle, goals.Alexandra Talty.\n\n They left on October 1, 2013. Traveling from west to the east, they started in Panama, spending six months backpacking around Central America. They then flew to Europe, made their way to Morocco and topped off their travel with two years in Asia. Over the course of nearly five years, they saw thirty countries together while dedicating themselves to a life of financial freedom.\n There were a few rules. Travel slow. Stick to carry-on only. Go where the dollar is strong.Book short stays online then re-negotiate in person. Search alternate flight routes and take advantage of budget airlines.\n Thanks to their strong budget skills, and Tim Ferriss' Dreamline sheet, these long term honeymooners were able to travel the world and achieve financial freedom.Amirah and Jarrell Cook.\n When they finally returned to the United States four and half years later, Amirah says a lot of their friends and family thought what they did was incredible. For the writer, and her painter husband, she says the decision to leave was easy.\n She says, 'what?'\n Thanks to Tim Ferriss' Sreamline sheet and her strong budget skills, Amirah Cook has been able to follow her dreams of long term travel and financial freedom.Amirah Cook.\n Working remotely, the pair traveled frugally as they made their way across continents. With a lower cost of living, and higher quality of life, the pair were able to launch their creative careers. Jarell painted and Amirah built up her writing portfolio, eventually writing her a book on budget travel and her first romance novella. Although now they are no longer budget travelers, the lessons from their younger days have stuck with them, helping them achieve their own version of financial freedom.\n";
        String copy6 = "How to plan, and budget, for long term travel.\n The biggest trick for achieving long term travel is to , says Amirah.\n Amirah and Jarrell Cook spent their twenties traveling the world together. Here they are in Florence, Italy in front of the Duomo or the Cathedral of Santa Maria del Fiore.Amirah and Jarrell Cook.\n The 31-year old recommends Tim Ferriss’ Dreamline sheet from the bestselling tome, The 4-Hour Work Week to help outline what you need to do to accomplish your dreams.  (The sheet is available for download here.) The graphic can be used to plan anything from buying a house to achieving financial freedom, and Amirah thinks it works especially well for long term travel.\n Tim Ferriss' Dreamline worksheet.Tim Ferriss.\n“It teaches you to break down these ideas that you have decided are unattainable,” says Amirah. “Once you break them down you see how accessible they are.”\n After focusing on your goal, the next step is the budget, says Amirah. Her number one way to stay on track is to use cash envelopes, similar to my oft-espoused ATM budget. Every month the millennial makes envelopes with labels like food or entertainment. She then puts her allocated amount of money into them. Once the cash is gone, she doesn't spend anymore on that category. Although Amirah admits debit cards and credit cards are easier, she finds it much more difficult to track her spending with plastic.\n Jarrell Cook enjoying the good life in Thailand, one of the couple's favorite long term travel destinations for millennials.Amirah Cook.\n Once you get the financials down, it's time for the fun stuff: deciding where you actually want to live or travel long-term. It’s important to consider both what kind of lifestyle you want and how much you can pay for it.\n“You are able to live a global lifestyle for the same cost as a two-bedroom apt in your hometown,” says Amirah, pointing out that a two-bedroom in Bali can run around $500.";
        String copy7 = "She believes that finding a low cost of living place does not \"always mean a sacrifice in your lifestyle.\n The key is to choosing a country that caters to your individual preferences. Since Amirah is a writer and  social media influencer, it’s important for her to live somewhere with good internet. She also prefers places with a warm climate where English is used for daily transactions.\n Come up with your list of must-haves. And then pick up a map of the world and see where those can be achieved. As long as you stick to your key qualifications, you can be flexible with pretty much everything else. The world is literally your oyster.\n If you need more information on local cost of living, the site Numbeo has an excellent calculator that breaks down everything from apartments to dinners to transportation.\n Where $1,5000 A Month Can Get You In The World.\n Although she and husband Jarrell's budget travel days are behind them, here are Amirah's favorite locations where you can survive on $1,5000 a month, as well as a few alternate suggestions that provide similar experiences.\n She believes that finding a low cost of living place does not \"always mean a sacrifice in your lifestyle.\n The key is to choosing a country that caters to your individual preferences. Since Amirah is a writer and  social media influencer, it’s important for her to live somewhere with good internet. She also prefers places with a warm climate where English is used for daily transactions.\n Come up with your list of must-haves. And then pick up a map of the world and see where those can be achieved. As long as you stick to your key qualifications, you can be flexible with pretty much everything else. The world is literally your oyster.\n If you need more information on local cost of living, the site Numbeo has an excellent calculator that breaks down everything from apartments to dinners to transportation.\n Where $1,5000 A Month Can Get You In The World.\n";
        String copy8 = "HONG KONG (Reuters) - UBS (UBSG.S) allows all its staff to travel “freely in and out” of China and it is business as usual there, the Swiss bank said, after local authorities last week asked one of its bankers to delay her departure from Beijing to meet with officials.\n + The logo of Swiss bank UBS is seen at the company's headquarters in Zurich, February 10, 2015. REUTERS/Arnd Wiegmann/File Photo\n + That move by the Chinese authorities led to UBS asking its wealth management staff to reconsider any travel plans to China, a person familiar with the matter told Reuters on Saturday.\n + UBS would like to confirm that we allow all our staff to travel freely in and out of the country and it is business as usual for us in China,” the bank said in a statement issued to Reuters on Tuesday.\n + UBS has had a strong franchise in China for 30 years and remains fully committed to further developing our business on the mainland.\n The Singapore-based UBS banker, who is a client relationship manager in the wealth management unit, was last week asked to delay departure from Beijing and remain in China to meet with local authority officials this week. Her identity was not known.\n While the purpose of the banker’s meeting with authorities is not clear and UBS has declined to comment on the matter, the uncertainty led several of its rivals to ask private banking staff to reconsider trips to China.\n Their caution highlighted the risks involved for global private banks in pursuing what is arguably the biggest opportunity worldwide in the wealth management business.\n China is the biggest growth driver of the wealth industry in Asia with its large and growing pool of millionaires and billionaires spawned by the country’s booming technology sector, making it a key battleground for global private banks.\n But its financial sector is under sharp scrutiny as Beijing attempts to lower high debt levels in the economy and curb an outflow of capital from the country to shore up the yuan, meaning there is very little room for error by industry players.\n";
        String copy9 = "We arrived to Hoi An fairly late at night, however when we did arrive we were pleasantly surprised at the hotel. The hotel itself was a rather lovely building but when we got to our room we found it had been prepared in such a way to make it feel special. There were flowers on the bed, a little message and even a little story waiting for us. It just felt very considered and gave a nice touch to the beginning of our stay. \n The next morning we were up and off fairly early for a walk with our guide to show us around the city. We made our way towards the old town but even on the way there was some rather nice architecture. It felt very different from the modern cities we had been spending time in basically since Malaysia.\n A ticket was required to be in the old town. They didn't check it on entry or exit, however I believe if you were caught without it you could be fined. The ticket included entry to some historical buildings as well as some shows, however unfortunately we didn't really have enough time in Hoi An to take full advantage of all the ticket had to offer.\n We were walked around the old town, and I was in awe. It was just so beautiful and it looked like it had come straight off a postcard. I am pretty sure it was a total tourist trap, and not \"authentic\" but to be honest that didn't bother me it was beautiful and clearly was daily life for those who lived in the area.";
        String copy10 = "LISBON (Reuters) - London’s popularity among Europe’s tech startup hubs has slumped as Brexit approaches and the city only kept its top spot in an European industry survey published on Tuesday by a narrow margin.\n Canary Wharf skyline and the City of London can be seen from the Sea Containers building in London, Britain, October 11, 2018. REUTERS/Henry Nicholls\n The survey of 540 tech founders showed that London’s popularity dropped to 41 percent in 2018 in a weighted vote, down from 55 percent in 2017. Berlin followed with 40 percent, according to the survey by the European Startup Initiative, a nonprofit organization.\n London’s popularity is partly because it attracts more investment money for startups than anywhere else. It captured 53 percent of all startup investment in the European Union last year, the survey said.\n But after Brexit it might become more difficult or less attractive for tech startups to base themselves in London.\n“With Brexit looming the question is pressing, how the still fragile network of European startup hubs will react when an important bloodline is pinched off,” the organization said in a statement.\n The second tier of European startup hubs was unchanged from the previous year with Barcelona and Paris remaining in third and fourth position with around 20 percent of the vote each.\n The biggest gainer was Lisbon, which jumped into fifth place from eighth with 12 percent of the vote, ahead of Amsterdam, which dropped into sixth place from fifth. Lisbon has gained ground thanks to the city hosting Europe’s largest tech event, the Web Summit.\n The survey found the top five cities received about 50 percent of all founders’ votes.\n Dublin and Stockholm fell out of the top 10, replaced by Munich and Milan. Zurich jumped into ninth position thanks to its popularity among fintech specialists, followed by Copenhagen.\n The survey’s main question to tech company founders was: “Where would you start if you could begin all over again?”";
        String copy11 = "Earnings season is still in its early days, but a troubling pattern has emerged.\n It was exemplified Tuesday by Caterpillar. The global maker of heavy equipment reported third-quarter profits that topped Wall Street's expectations. And yet, its shares slumped by as much as 7% in trading after the company warned that its material costs were rising.\n Several other companies that have beaten Wall Street profit expectations in the third quarter have not been rewarded by investors after the fact. And according to Bank of America Merrill Lynch, it's a clear signal that the record-setting bull market in stocks is approaching its end.\n One of the signposts that was triggered since 2Q17 continues to worsen,\" Savita Subramanian, BAML's head of US equity and quant strategy, said in a note to clients on Sunday.\n A lack of reward for EPS & sales beats is typically a later-stage bull market signal, suggesting that the good news is priced in. There have been four quarters since the second quarter of 2017 in which companies that beat Wall Street's expectations were rewarded the next day with a share-price rally of less than 1 percentage point, Subramanian added.\n But this is the first quarter since 2000 in which companies that beat on earnings are seeing a negative reaction in the stock market.\n Bank of America Merrill Lynch\n Every company's case is different, but some common themes are emerging that are likely to dominate investors' minds as earnings season enters its peak period.\n One of these themes is forward guidance on the impact of US tariffs on Chinese goods, which now apply to $250 billion worth of imports — about half of all that is brought in from the country. Caterpillar said it expected cost cuts to offset the higher prices caused by tariffs, but investors are skeptical.\n Another overarching theme on investors' minds is that earnings growth may peak this quarter.\n Subramanian cautioned clients not to confuse that with peaking profits. She noted that returns in the three and six months after a peak in earnings growth were still positive and close to average.\n And so, perhaps the emergence of this trend should not be taken as a sell-all trigger. Still, it may be another reason to start positioning for the next bear market in earnest.";
        String copy12 = "She believes that finding a low cost of living place does not \"always mean a sacrifice in your lifestyle.\n The key is to choosing a country that caters to your individual preferences. Since Amirah is a writer and  social media influencer, it’s important for her to live somewhere with good internet. She also prefers places with a warm climate where English is used for daily transactions.\n Come up with your list of must-haves. And then pick up a map of the world and see where those can be achieved. As long as you stick to your key qualifications, you can be flexible with pretty much everything else. The world is literally your oyster.\n If you need more information on local cost of living, the site Numbeo has an excellent calculator that breaks down everything from apartments to dinners to transportation.\n Where $1,5000 A Month Can Get You In The World.\n Although she and husband Jarrell's budget travel days are behind them, here are Amirah's favorite locations where you can survive on $1,5000 a month, as well as a few alternate suggestions that provide similar experiences.\n She believes that finding a low cost of living place does not \"always mean a sacrifice in your lifestyle.\n The key is to choosing a country that caters to your individual preferences. Since Amirah is a writer and  social media influencer, it’s important for her to live somewhere with good internet. She also prefers places with a warm climate where English is used for daily transactions.\n Come up with your list of must-haves. And then pick up a map of the world and see where those can be achieved. As long as you stick to your key qualifications, you can be flexible with pretty much everything else. The world is literally your oyster.\n If you need more information on local cost of living, the site Numbeo has an excellent calculator that breaks down everything from apartments to dinners to transportation.\n Where $1,5000 A Month Can Get You In The World.\n";
        String copy13 = "We arrived to Hoi An fairly late at night, however when we did arrive we were pleasantly surprised at the hotel. The hotel itself was a rather lovely building but when we got to our room we found it had been prepared in such a way to make it feel special. There were flowers on the bed, a little message and even a little story waiting for us. It just felt very considered and gave a nice touch to the beginning of our stay. \n The next morning we were up and off fairly early for a walk with our guide to show us around the city. We made our way towards the old town but even on the way there was some rather nice architecture. It felt very different from the modern cities we had been spending time in basically since Malaysia.\n A ticket was required to be in the old town. They didn't check it on entry or exit, however I believe if you were caught without it you could be fined. The ticket included entry to some historical buildings as well as some shows, however unfortunately we didn't really have enough time in Hoi An to take full advantage of all the ticket had to offer.\n We were walked around the old town, and I was in awe. It was just so beautiful and it looked like it had come straight off a postcard. I am pretty sure it was a total tourist trap, and not \"authentic\" but to be honest that didn't bother me it was beautiful and clearly was daily life for those who lived in the area.";
        String copy14 = "How to plan, and budget, for long term travel.\n The biggest trick for achieving long term travel is to , says Amirah.\n Amirah and Jarrell Cook spent their twenties traveling the world together. Here they are in Florence, Italy in front of the Duomo or the Cathedral of Santa Maria del Fiore.Amirah and Jarrell Cook.\n The 31-year old recommends Tim Ferriss’ Dreamline sheet from the bestselling tome, The 4-Hour Work Week to help outline what you need to do to accomplish your dreams.  (The sheet is available for download here.) The graphic can be used to plan anything from buying a house to achieving financial freedom, and Amirah thinks it works especially well for long term travel.\n Tim Ferriss' Dreamline worksheet.Tim Ferriss.\n“It teaches you to break down these ideas that you have decided are unattainable,” says Amirah. “Once you break them down you see how accessible they are.”\n After focusing on your goal, the next step is the budget, says Amirah. Her number one way to stay on track is to use cash envelopes, similar to my oft-espoused ATM budget. Every month the millennial makes envelopes with labels like food or entertainment. She then puts her allocated amount of money into them. Once the cash is gone, she doesn't spend anymore on that category. Although Amirah admits debit cards and credit cards are easier, she finds it much more difficult to track her spending with plastic.\n Jarrell Cook enjoying the good life in Thailand, one of the couple's favorite long term travel destinations for millennials.Amirah Cook.\n Once you get the financials down, it's time for the fun stuff: deciding where you actually want to live or travel long-term. It’s important to consider both what kind of lifestyle you want and how much you can pay for it.\n“You are able to live a global lifestyle for the same cost as a two-bedroom apt in your hometown,” says Amirah, pointing out that a two-bedroom in Bali can run around $500.";
        String copy15 = "While in Tokyo we had a few experiences with robots that I would like to share with you, most of these are not necessarily robots in the traditional sense, but more for entertainment. We have been to Tokyo before and at that point we did most of the touristy things, including seeing Asimo, so this time we just decided to have some fun.\nThe first robot we saw was also the first thing we did in Tokyo thanks to my husband, as he was obsessed with going to see this Robot for months before we even got here. I am talking about Unicorn Gundam. The first time we were in Tokyo we saw the original Gundam, but it has since been replaced by Unicorn Gundam.\nUnless you are very into Japanese culture, you are probably fairly lost right now. Mobile Suit Gundam is an anime series that started in the eighties. It is basically the story of a boy genius who uses the giant robot suit, designed by his father, to fight in and end the war raging in the galaxy. You may be more familiar with Power Rangers, which was the live action show inspired by Gundam but was more focused on selling toys. As with a lot of these types of series, it went through a series of generations of bigger, more powerful robots, including Unicorn Gundam.\nSo at Gundam Front there is a life-sized replica, previously of the original RX-78-2 Gundam and now Unicorn Gundam. It is quite impressive to see a giant robot in front of a shopping mall.\nWe did a lot of wandering around Tokyo and while I intend to dedicate a post to just that later on, one thing we came across during our wanderings was relevent to this post. We were just wandering through a mall relatively close to Gundam front where we saw a lady behind an information desk, except it wasn't a lady it was actually a robot!";
        String copy16 = "Third-grade students at the Douglass G Grafflin School in Chappaqua, New York, participate in an interactive learning session with the Nintendo Labo: Variety Kit for the Nintendo Switch system, led by Rebecca Rufo-Tepper, Co-Executive Director of the Institute of Play.(Photo: Nintendo of America)\n Nintendo Labo is going to school.  \n The video game maker is teaming up with the non-profit Institute of Play to bring its Do-It-Yourself (DIY) Labo cardboard gaming kits to 100 elementary schools around the country. \n“Our goal is to help teachers and students have fun with the basic principles of science, technology, engineering, art and mathematics, collectively known as STEAM,” says Nintendo of America President and COO Reggie Fils-Aime. “We believe Nintendo Labo can be a powerful learning tool to foster 21st Century skills such as communication, collaboration, creativity, critical thinking and problem solving.”\n The program aims to reach some 2,000 students between ages 8 and 11 during the 2018-2019 school year.\n Nintendo release cardboard gaming system called Nintendo Labo, Eleven year-old Samuel Baig.\n The Labo kits, which I gave a positive review in April through the eyes of my 11-year old son, Samuel, are a bit challenging to pigeonhole. Think of them as kits that marry the required Nintendo Switch portable video gaming system with pieces of cardboard that a kid can bend and fold into various so-called “Toy-Con” projects, including a miniature piano (that can play real notes), fishing rod and robot. \n Step-by-step animations appear on the Switch to help students build their projects. \n The schools that end up participating as part of the program will receive two Nintendo Switch systems and Labo “Variety Kits” at no cost, along with extra cardboard to accommodate multiple students in a classroom. Nintendo and the Institute of Play have also put together a guide for teachers. \n The required Nintendo Switch normally lists for $299.99, and the Labo cardboard is pricey, too: $69.99 for a variety pack with five projects, or $79.99 for the robot kit.\n Schools can still apply to be part of the program. Arana Shapiro, the co-director of the Institute of Play, says the organization is seeking public and private schools, and schools in suburban, urban and rural areas that represent socioeconomic diversity.";
        String copy17 = "Earnings season is still in its early days, but a troubling pattern has emerged.\n It was exemplified Tuesday by Caterpillar. The global maker of heavy equipment reported third-quarter profits that topped Wall Street's expectations. And yet, its shares slumped by as much as 7% in trading after the company warned that its material costs were rising.\n Several other companies that have beaten Wall Street profit expectations in the third quarter have not been rewarded by investors after the fact. And according to Bank of America Merrill Lynch, it's a clear signal that the record-setting bull market in stocks is approaching its end.\n One of the signposts that was triggered since 2Q17 continues to worsen,\" Savita Subramanian, BAML's head of US equity and quant strategy, said in a note to clients on Sunday.\n A lack of reward for EPS & sales beats is typically a later-stage bull market signal, suggesting that the good news is priced in. There have been four quarters since the second quarter of 2017 in which companies that beat Wall Street's expectations were rewarded the next day with a share-price rally of less than 1 percentage point, Subramanian added.\n But this is the first quarter since 2000 in which companies that beat on earnings are seeing a negative reaction in the stock market.\n Bank of America Merrill Lynch\n Every company's case is different, but some common themes are emerging that are likely to dominate investors' minds as earnings season enters its peak period.\n One of these themes is forward guidance on the impact of US tariffs on Chinese goods, which now apply to $250 billion worth of imports — about half of all that is brought in from the country. Caterpillar said it expected cost cuts to offset the higher prices caused by tariffs, but investors are skeptical.\n Another overarching theme on investors' minds is that earnings growth may peak this quarter.\n Subramanian cautioned clients not to confuse that with peaking profits. She noted that returns in the three and six months after a peak in earnings growth were still positive and close to average.\n And so, perhaps the emergence of this trend should not be taken as a sell-all trigger. Still, it may be another reason to start positioning for the next bear market in earnest.";
        String copy18 = "How to plan, and budget, for long term travel.\n The biggest trick for achieving long term travel is to , says Amirah.\n Amirah and Jarrell Cook spent their twenties traveling the world together. Here they are in Florence, Italy in front of the Duomo or the Cathedral of Santa Maria del Fiore.Amirah and Jarrell Cook.\n The 31-year old recommends Tim Ferriss’ Dreamline sheet from the bestselling tome, The 4-Hour Work Week to help outline what you need to do to accomplish your dreams.  (The sheet is available for download here.) The graphic can be used to plan anything from buying a house to achieving financial freedom, and Amirah thinks it works especially well for long term travel.\n Tim Ferriss' Dreamline worksheet.Tim Ferriss.\n“It teaches you to break down these ideas that you have decided are unattainable,” says Amirah. “Once you break them down you see how accessible they are.”\n After focusing on your goal, the next step is the budget, says Amirah. Her number one way to stay on track is to use cash envelopes, similar to my oft-espoused ATM budget. Every month the millennial makes envelopes with labels like food or entertainment. She then puts her allocated amount of money into them. Once the cash is gone, she doesn't spend anymore on that category. Although Amirah admits debit cards and credit cards are easier, she finds it much more difficult to track her spending with plastic.\n Jarrell Cook enjoying the good life in Thailand, one of the couple's favorite long term travel destinations for millennials.Amirah Cook.\n Once you get the financials down, it's time for the fun stuff: deciding where you actually want to live or travel long-term. It’s important to consider both what kind of lifestyle you want and how much you can pay for it.\n“You are able to live a global lifestyle for the same cost as a two-bedroom apt in your hometown,” says Amirah, pointing out that a two-bedroom in Bali can run around $500.";
        String copy19 = "She believes that finding a low cost of living place does not \"always mean a sacrifice in your lifestyle.\n The key is to choosing a country that caters to your individual preferences. Since Amirah is a writer and  social media influencer, it’s important for her to live somewhere with good internet. She also prefers places with a warm climate where English is used for daily transactions.\n Come up with your list of must-haves. And then pick up a map of the world and see where those can be achieved. As long as you stick to your key qualifications, you can be flexible with pretty much everything else. The world is literally your oyster.\n If you need more information on local cost of living, the site Numbeo has an excellent calculator that breaks down everything from apartments to dinners to transportation.\n Where $1,5000 A Month Can Get You In The World.\n Although she and husband Jarrell's budget travel days are behind them, here are Amirah's favorite locations where you can survive on $1,5000 a month, as well as a few alternate suggestions that provide similar experiences.\n She believes that finding a low cost of living place does not \"always mean a sacrifice in your lifestyle.\n The key is to choosing a country that caters to your individual preferences. Since Amirah is a writer and  social media influencer, it’s important for her to live somewhere with good internet. She also prefers places with a warm climate where English is used for daily transactions.\n Come up with your list of must-haves. And then pick up a map of the world and see where those can be achieved. As long as you stick to your key qualifications, you can be flexible with pretty much everything else. The world is literally your oyster.\n If you need more information on local cost of living, the site Numbeo has an excellent calculator that breaks down everything from apartments to dinners to transportation.\n Where $1,5000 A Month Can Get You In The World.\n";
        String copy20 = "We arrived to Hoi An fairly late at night, however when we did arrive we were pleasantly surprised at the hotel. The hotel itself was a rather lovely building but when we got to our room we found it had been prepared in such a way to make it feel special. There were flowers on the bed, a little message and even a little story waiting for us. It just felt very considered and gave a nice touch to the beginning of our stay. \n The next morning we were up and off fairly early for a walk with our guide to show us around the city. We made our way towards the old town but even on the way there was some rather nice architecture. It felt very different from the modern cities we had been spending time in basically since Malaysia.\n A ticket was required to be in the old town. They didn't check it on entry or exit, however I believe if you were caught without it you could be fined. The ticket included entry to some historical buildings as well as some shows, however unfortunately we didn't really have enough time in Hoi An to take full advantage of all the ticket had to offer.\n We were walked around the old town, and I was in awe. It was just so beautiful and it looked like it had come straight off a postcard. I am pretty sure it was a total tourist trap, and not \"authentic\" but to be honest that didn't bother me it was beautiful and clearly was daily life for those who lived in the area.";
        String copy21 = "Third-grade students at the Douglass G Grafflin School in Chappaqua, New York, participate in an interactive learning session with the Nintendo Labo: Variety Kit for the Nintendo Switch system, led by Rebecca Rufo-Tepper, Co-Executive Director of the Institute of Play.(Photo: Nintendo of America)\n Nintendo Labo is going to school.  \n The video game maker is teaming up with the non-profit Institute of Play to bring its Do-It-Yourself (DIY) Labo cardboard gaming kits to 100 elementary schools around the country. \n“Our goal is to help teachers and students have fun with the basic principles of science, technology, engineering, art and mathematics, collectively known as STEAM,” says Nintendo of America President and COO Reggie Fils-Aime. “We believe Nintendo Labo can be a powerful learning tool to foster 21st Century skills such as communication, collaboration, creativity, critical thinking and problem solving.”\n The program aims to reach some 2,000 students between ages 8 and 11 during the 2018-2019 school year.\n Nintendo release cardboard gaming system called Nintendo Labo, Eleven year-old Samuel Baig.\n The Labo kits, which I gave a positive review in April through the eyes of my 11-year old son, Samuel, are a bit challenging to pigeonhole. Think of them as kits that marry the required Nintendo Switch portable video gaming system with pieces of cardboard that a kid can bend and fold into various so-called “Toy-Con” projects, including a miniature piano (that can play real notes), fishing rod and robot. \n Step-by-step animations appear on the Switch to help students build their projects. \n The schools that end up participating as part of the program will receive two Nintendo Switch systems and Labo “Variety Kits” at no cost, along with extra cardboard to accommodate multiple students in a classroom. Nintendo and the Institute of Play have also put together a guide for teachers. \n The required Nintendo Switch normally lists for $299.99, and the Labo cardboard is pricey, too: $69.99 for a variety pack with five projects, or $79.99 for the robot kit.\n Schools can still apply to be part of the program. Arana Shapiro, the co-director of the Institute of Play, says the organization is seeking public and private schools, and schools in suburban, urban and rural areas that represent socioeconomic diversity.";
        String copy22 = "While in Tokyo we had a few experiences with robots that I would like to share with you, most of these are not necessarily robots in the traditional sense, but more for entertainment. We have been to Tokyo before and at that point we did most of the touristy things, including seeing Asimo, so this time we just decided to have some fun.\nThe first robot we saw was also the first thing we did in Tokyo thanks to my husband, as he was obsessed with going to see this Robot for months before we even got here. I am talking about Unicorn Gundam. The first time we were in Tokyo we saw the original Gundam, but it has since been replaced by Unicorn Gundam.\nUnless you are very into Japanese culture, you are probably fairly lost right now. Mobile Suit Gundam is an anime series that started in the eighties. It is basically the story of a boy genius who uses the giant robot suit, designed by his father, to fight in and end the war raging in the galaxy. You may be more familiar with Power Rangers, which was the live action show inspired by Gundam but was more focused on selling toys. As with a lot of these types of series, it went through a series of generations of bigger, more powerful robots, including Unicorn Gundam.\nSo at Gundam Front there is a life-sized replica, previously of the original RX-78-2 Gundam and now Unicorn Gundam. It is quite impressive to see a giant robot in front of a shopping mall.\nWe did a lot of wandering around Tokyo and while I intend to dedicate a post to just that later on, one thing we came across during our wanderings was relevent to this post. We were just wandering through a mall relatively close to Gundam front where we saw a lady behind an information desk, except it wasn't a lady it was actually a robot!";
        String copy23 = "Earnings season is still in its early days, but a troubling pattern has emerged.\n It was exemplified Tuesday by Caterpillar. The global maker of heavy equipment reported third-quarter profits that topped Wall Street's expectations. And yet, its shares slumped by as much as 7% in trading after the company warned that its material costs were rising.\n Several other companies that have beaten Wall Street profit expectations in the third quarter have not been rewarded by investors after the fact. And according to Bank of America Merrill Lynch, it's a clear signal that the record-setting bull market in stocks is approaching its end.\n One of the signposts that was triggered since 2Q17 continues to worsen,\" Savita Subramanian, BAML's head of US equity and quant strategy, said in a note to clients on Sunday.\n A lack of reward for EPS & sales beats is typically a later-stage bull market signal, suggesting that the good news is priced in. There have been four quarters since the second quarter of 2017 in which companies that beat Wall Street's expectations were rewarded the next day with a share-price rally of less than 1 percentage point, Subramanian added.\n But this is the first quarter since 2000 in which companies that beat on earnings are seeing a negative reaction in the stock market.\n Bank of America Merrill Lynch\n Every company's case is different, but some common themes are emerging that are likely to dominate investors' minds as earnings season enters its peak period.\n One of these themes is forward guidance on the impact of US tariffs on Chinese goods, which now apply to $250 billion worth of imports — about half of all that is brought in from the country. Caterpillar said it expected cost cuts to offset the higher prices caused by tariffs, but investors are skeptical.\n Another overarching theme on investors' minds is that earnings growth may peak this quarter.\n Subramanian cautioned clients not to confuse that with peaking profits. She noted that returns in the three and six months after a peak in earnings growth were still positive and close to average.\n And so, perhaps the emergence of this trend should not be taken as a sell-all trigger. Still, it may be another reason to start positioning for the next bear market in earnest.";
        String copy24 = "Third-grade students at the Douglass G Grafflin School in Chappaqua, New York, participate in an interactive learning session with the Nintendo Labo: Variety Kit for the Nintendo Switch system, led by Rebecca Rufo-Tepper, Co-Executive Director of the Institute of Play.(Photo: Nintendo of America)\n Nintendo Labo is going to school.  \n The video game maker is teaming up with the non-profit Institute of Play to bring its Do-It-Yourself (DIY) Labo cardboard gaming kits to 100 elementary schools around the country. \n“Our goal is to help teachers and students have fun with the basic principles of science, technology, engineering, art and mathematics, collectively known as STEAM,” says Nintendo of America President and COO Reggie Fils-Aime. “We believe Nintendo Labo can be a powerful learning tool to foster 21st Century skills such as communication, collaboration, creativity, critical thinking and problem solving.”\n The program aims to reach some 2,000 students between ages 8 and 11 during the 2018-2019 school year.\n Nintendo release cardboard gaming system called Nintendo Labo, Eleven year-old Samuel Baig.\n The Labo kits, which I gave a positive review in April through the eyes of my 11-year old son, Samuel, are a bit challenging to pigeonhole. Think of them as kits that marry the required Nintendo Switch portable video gaming system with pieces of cardboard that a kid can bend and fold into various so-called “Toy-Con” projects, including a miniature piano (that can play real notes), fishing rod and robot. \n Step-by-step animations appear on the Switch to help students build their projects. \n The schools that end up participating as part of the program will receive two Nintendo Switch systems and Labo “Variety Kits” at no cost, along with extra cardboard to accommodate multiple students in a classroom. Nintendo and the Institute of Play have also put together a guide for teachers. \n The required Nintendo Switch normally lists for $299.99, and the Labo cardboard is pricey, too: $69.99 for a variety pack with five projects, or $79.99 for the robot kit.\n Schools can still apply to be part of the program. Arana Shapiro, the co-director of the Institute of Play, says the organization is seeking public and private schools, and schools in suburban, urban and rural areas that represent socioeconomic diversity.";


        List<Category> category1 = new ArrayList<>();
        category1.add(technology);

        List<Category> category2 = new ArrayList<>();
        category2.add(health);

        List<Category> category3 = new ArrayList<>();
        category3.add(travel);

        List<Category> categories4 = new ArrayList<>();
        categories4.add(travel);
        categories4.add(technology);

        List<Category> categories5 = new ArrayList<>();
        categories5.add(politics);

        List<Category> categories6 = new ArrayList<>();
        categories5.add(sport);


        Article article1 = new Article("CodeClan wins award", "CodeClan, digital skills academy, has won the biggest award.", copy1, "codeclan_thumb.png", "codeclan_thumb.png", date1, category1, johnSmith);
        articleRepository.save(article1);

        Article article2 = new Article("Storm enters UK", "Storm due to hit on Friday.", copy6, "storm_banner.jpg", "storm_thumb.jpg", date2, category2, petraCook);
        articleRepository.save(article2);

        Article article3 = new Article("Take Me Back To Hoi An", "Historic City In Vietnam", copy2, "take_me_back_to_hoi_an_banner.jpg", "take_me_back_to_hoi_an_thumb.jpg", date3, category3, samLloyd);
        articleRepository.save(article3);

        Article article4 = new Article("Sunrise? Wat Sunrise", "Unbelievable views at Angkor Wat", copy3, "angkor_banner.jpg", "angkor_thumb.jpg", date5, category3, johnSmith);
        articleRepository.save(article4);

        Article article5 = new Article("Tokyo Robots", "Gundam, Help Desks and Restaurants", copy4, "robot_banner.jpg", "robot_thumb.jpg", date4, categories4, keithGreen);
        articleRepository.save(article5);

        Article article6 = new Article("UBS to China", "UBS says it allows staff to travel 'freely' to China after banker's departure delayed", copy5, "china_thumb.jpg", "china_banner.jpg", date6, categories5, samLloyd);
        articleRepository.save(article6);

        Article article7 = new Article("Budget Travel", "How To Travel The World On $1,500 A Month", copy7, "budget_banner.jpg", "budget_thumb.jpg", date7, category1, petraCook);
        articleRepository.save(article7);

        Article article8 = new Article("Brexit is Coming", "London's popularity as tech hub slumps ahead of Brexit", copy8, "brexit_banner.jpg", "brexit_thumb.jpg", date8, categories5, maryPeterson);
        articleRepository.save(article8);

        Article article9 = new Article("Stocks Crashing", "Stocks are doing something not seen since the tech bubble", copy9, "stock_banner.jpg", "stock_thumb.jpg", date9, categories5, petraCook);
        articleRepository.save(article9);

        Article article10 = new Article("Nintendo's New Toy", "Nintendo takes Labo gaming kits to school to get kids interested in science, math and tech", copy10, "nintendo_banner.jpg", "nintendo_thumb.jpg", date10, category1, samLloyd);
        articleRepository.save(article10);

        Article article11 = new Article("New Breakthrough in Parkinson's Treatment", "Researchers have promising results", copy11, "treatment_banner.jpg", "treatment_thumb.jpg", date11, category2, johnSmith);
        articleRepository.save(article11);

        Article article12 = new Article("On The Go Mobile News", "Take your mobile abroad for free.", copy12, "mobile_banner.jpg", "mobile_thumb.jpg", date12, categories4, keithGreen);
        articleRepository.save(article12);

        Article article13 = new Article("Local Team Wins Cup", "First time in 17 years.", copy13, "win_banner.jpg", "win_thumb.jpg", date13, categories6, johnSmith);
        articleRepository.save(article13);

        Article article14 = new Article("Best Ways to Handle the Cold", "Bed rest is not the way forward, doctors say.", copy14, "cold_thumb.jpg", "cold_banner.jpg", date14, category2, petraCook);
        articleRepository.save(article14);

        Article article15 = new Article("Boxer Retires", "Too many knocks, she says.", copy15, "boxer_banner.jpg", "boxer_thumb.jpg", date15, categories6, maryPeterson);
        articleRepository.save(article15);

        Article article16 = new Article("Holiday-Makers Enjoy Lack of iPad", "More time to relax, they say.", copy16, "ipad_banner.jpg", "ipad_thumb.jpg", date16, categories4, samLloyd);
        articleRepository.save(article16);

        Article article17 = new Article("Rugby Growing in Popularity", "Focus in schools cited as increasing fans.", copy17, "rugby_banner.jpg", "rugby_thumb.jpg", date17, categories6, keithGreen);
        articleRepository.save(article17);

        Article article18 = new Article("Eat Yourself Healthy", "Diet key to long life.", copy18, "diet_banner.jpg", "diet_thumb.jpg", date18, category2, johnSmith);
        articleRepository.save(article18);

        Article article19 = new Article("Broken Legs are the Worst", "Kids struggle to catch up at school.", copy19, "leg_banner.jpg", "leg_thumb.jpg", date19, category2, petraCook);
        articleRepository.save(article19);

        Article article20 = new Article("General Election", "PM calls election for next month.", copy20, "election_banner.jpg", "election_thumb.jpg", date20, categories5, maryPeterson);
        articleRepository.save(article20);

        Article article21 = new Article("New iPhone", "Apple will release next month.", copy21, "iphone_banner.jpg", "iphone_thumb.jpg", date21, category1, samLloyd);
        articleRepository.save(article21);

        Article article22 = new Article("Local MP to Resign", "Mr Jones will leave soon.", copy22, "mp_banner.jpg", "mp_thumb.jpg", date22, categories5, keithGreen);
        articleRepository.save(article22);

        Article article23 = new Article("Large Development for Glasgow", "1,000 new jobs to be created.", copy23, "development_banner.jpg", "development_thumb.jpg", date23, category1, johnSmith);
        articleRepository.save(article23);

        Article article24 = new Article("Fly to Iceland from Glasgow", "Airline launches new route.", copy24, "iceland_banner.jpg", "iceland_thumb.jpg", date24, category3, petraCook);
        articleRepository.save(article24);


    }

}
